# action.yaml
name: 'Python Blacken'
description: 'Customisable GitHub action to use black to check Python code in your repository'
branding:
  icon: 'code'
  color: 'black'
inputs:
  path:
    description: 'File or directory to run black on.'
    required: false
    default: '.'
  line-length:
    description: 'The number of characters allowed per line.'
    required: false
    default: '88'
  sanity-check:
    description: 'Sanity check [fast|safe]'
    required: false
    default: 'fast'
  only-check:
    description: 'Only check the files instead of modify them [yes|no] '
    required: false
    default: 'yes'

outputs:
  output:
    description: 'The output of black.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sanity-check }}
    - ${{ inputs.line-length }}
    - ${{ inputs.only-check }}
    - ${{ inputs.path }}
